import type { Metadata } from "next";

// import "./globals.css";
import "./globals.css"

// app/layout.tsx or RootLayout.tsx
import { Inter } from 'next/font/google';
import { CartProvider } from "./context/CartContext";
import { AuthProvider } from "./context/AuthContext";
import Navbar from "./components/Navbar";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased` }
      >
        <CartProvider>
          <AuthProvider>
             <Navbar />

            
        {children}
          </AuthProvider>

        
        </CartProvider>
      </body>
      
    </html>
  );
}
